from rest_framework_simplejwt.views import TokenObtainPairView
from backend.apps.usuarios.token_serealizer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer