# Generated by Django 5.2 on 2025-05-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Matriz', 'Matriz'), ('Reprodutor', 'Reprodutor'), ('Novilha', 'Novilha'), ('Novilho', 'Novilho'), ('Bezerro', 'Bezerro')], max_length=50)),
            ],
        ),
    ]
