# Generated by Django 5.2 on 2025-05-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='usuarios.fazenda'),
        ),
    ]
