# Generated by Django 5.2.1 on 2025-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pai_ou_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bezerros', to='animais.animal'),
        ),
    ]
