# Generated by Django 5.2.1 on 2025-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animal_pai_ou_mae'),
        ('pastagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pastagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='pastagens.pastagem'),
        ),
    ]
