# Generated by Django 5.2.1 on 2025-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_animal_pastagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
