# Generated by Django 5.2.1 on 2025-06-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0004_animal_pastagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('next_date', models.DateField()),
                ('status', models.CharField(choices=[('Aplicada', 'Aplicada'), ('Pendente', 'Pendente'), ('Atrasada', 'Atrasada')], max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='animais.animal')),
            ],
        ),
    ]
