# Generated by Django 5.2.1 on 2025-06-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Açude', 'Açude'), ('Rio', 'Rio'), ('Poço', 'Poço')], max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('current', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Adequado', 'Adequado'), ('Baixo', 'Baixo')], max_length=50)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_agua', to='usuarios.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Pastagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('current', models.IntegerField()),
                ('status', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular'), ('Em Recuperação', 'Em Recuperação')], max_length=50)),
                ('last_rotation', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastagens', to='usuarios.fazenda')),
            ],
        ),
    ]
